name: Back-end Build

on:
  push:
    branches:
      - back-end_drop
      - front-end_drop
      - ci/cd-pipeline-1
      - pipeline-test
      - pipeline2.0
      - front-end
      - back-end
      - dev-ops

  pull_request:
    branches:
      - main
      - back-end_drop
      - front-end_drop
      - front-end
      - back-end
      - dev-ops

jobs:
  back-end-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./src/back-end
    - name: JEST Report
      uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        json-glob: ./src/back-end/testOutput.json
        workdir: ./src/back-end