name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Node.js App
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}} # IP Address of Server
        key: ${{secrets.SSH_KEY}} # Private/Public Key of Server
        username: ${{secrets.SSH_USERNAME}} # user for Server

        script: |
          cd ../var/www/boojo.bitfrost.app/cse112-sp22-group1
          git reset --hard origin/main
          git pull origin main
          cd  src/back-end
          rm constants.js
          mv constants_prod.js constants.js
          PATH=$PATH:/${{secrets.SSH_USERNAME}}/.nvm/versions/node/v16.14.2/bin
          npm install
          cd ../front-end
          npm install
          npm run build
          cd ./prod
          npm install
          echo 'Deployed to DigitalOcean'